cdk/policies/minimal_permissions_for_cdk_deploy_and_destroy.json, cdk/policies/minimal_permissions_for_cf_ui_and_terraform.json
The two policies were sort of hard to compare as they were sorted differently and had different levels of indentation. I just loaded this into a python dict and spat it back out so they'd be the same.
=> Make formatting/sorting the same on both policies

cdk/domino/domino_stack.py, iam_policies/minimal_permissions_for_cf_ui_and_terraform.json
Goals:
- We want to give access to the same deployment images.
- We definitely want some specific EKS images. This comes for free because they are public and IAM doesn't affect them.
- We do not want to give a blanket access to each and every domino images in the same account because there can be images that are not in a deployment but still restricted.
- We do not care to limit to the account, this probably happens automatically because of "private" thing, we just do not want access to all images in the same account unless explicitly allowed.
Change summary:
1. Add ECR creation policy to the deploying role (this is not used right now but might be useful later).
2. Add explicit ECR deny policy that will prohibit pulling images from the same account if they are not marked as same …
=> Add ECR policies (PLAT-2132)

.gitignore, cdk/app.py, cdk/domino_cdk/__init__.py, cdk/domino_cdk/config_template.yaml, cdk/domino_cdk/eks_stack.py, cdk/domino_cdk/util.py, cdk/setup.py
PLAT-2246/PLAT-2247/PLAT-2230...
* dev deploys (proper reduced sizing)
* Because the control plane requires a minimum of 2 AZs, just reducing to 1 AZ like we've done in the past doesn't work. Need to _only_ scale down the ASG AZs instead.
* Add SSH keypair support
* Add SSM support
* Add an optional bastion instance
* Fix private API setting
=> Misc dev/access improvements

cdk/domino_cdk/eks_stack.py
The unmanaged node groups must require IMDSv2.
=> PLAT-1945: Require IMDSv2

cdk/domino_cdk/eks_stack.py, cdk/domino_cdk/util.py
If ami_id is not specified in managed user group, EKS automatically provides latest and greatest Linux2 image. AWS documentation vague hints that the nodes will be also automatically upgraded if a newer and greater Linux2 image emerges.
In this case EKS provides its bootstrap logic as a part in MIME/multipart and demands that any other user data was also in MIME/multipart so it can join the parts together.
user data is fed to cloud_init and MIME/multipart is one of the formats where multiple scripts are passed as parts.
Benefits for managed node groups:
1. We can have true auto-upgrading fully managed autoscaling group.
2. We can add "install ssm" logic and "tweak QPS in kubelet" as separate bash scripts that do not intersect with any custom user data.
Also, we can improve unmanaged node …
=> Improvements for custom ami and user data handling (PLAT-2266 and PLAT-2354)

cdk/domino_cdk/config/iam.py, cdk/domino_cdk/util.py, cdk/util.py, terraform/cloudformation.tf, terraform/iam.tf, terraform/variables.tf
Split the IAM policy in two at the last minute to reduce the chances of running into size restrictions during #24.
This PR adds support on the terraform module/terraform-config-generator portion for these multiple policies. Required for deployer integration.
=> PLAT-2142: Terraform support for multiple deploy policies

cdk/domino_cdk/agent.py, cdk/domino_cdk/aws_configurator.py, cdk/domino_cdk/config/base.py, cdk/domino_cdk/config/template.py, cdk/domino_cdk/domino_stack.py, cdk/domino_cdk/provisioners/efs.py, cdk/domino_cdk/provisioners/eks/__init__.py, cdk/domino_cdk/provisioners/eks/eks_cluster.py, cdk/domino_cdk/provisioners/eks/eks_iam.py, cdk/domino_cdk/provisioners/eks/eks_iam_roles_for_k8s.py, cdk/domino_cdk/provisioners/eks/eks_nodegroup.py, cdk/domino_cdk/provisioners/s3.py, cdk/domino_cdk/provisioners/vpc.py
We configure IAM roles to associate with service accounts in k8s. 
We have a switch to choose between the node level roles and service level nodes.
ECR permissions for the nodes are changed to the recommended for the worker nodes.
See code comments for more details.
=> Adding IAM roles for K8s service accounts (PLAT-2264)

cdk/domino_cdk/domino_stack.py, cdk/domino_cdk/util.py
* Running config is added to the stack as a CloudFormation output
* This is just a safety / tracking / visibility thing. ie you can recover your settings if you lose your local copy, or if you're looking at what's provisioned you can know what the settings were, etc.
* The agent template now goes through ruamel's dump instead of the standard yaml one
* Though the motivation was just not to have two different yaml dumpers in the same file, it has the advantage of preserving the order of the original structure, which mimics the order in the actual agent template
=> Save config as stack output + use ruamel for agent template output

cdk/domino_cdk/provisioners/efs.py, cdk/domino_cdk/provisioners/eks/eks_cluster.py, cdk/domino_cdk/provisioners/lambda_files/backup_post_creation_tasks.py, cdk/domino_cdk/provisioners/lambda_files/cluster_post_creation_tasks.py, cdk/domino_cdk/provisioners/lambda_files/cluster_post_deletion_tasks.py, cdk/domino_cdk/provisioners/lambda_utils.py
JIRA: https://dominodatalab.atlassian.net/browse/PLAT-2515
Fixes:
1. Parameters are passed to lambdas using custom resource parameters, not environmant.
2. Thanks to that, now the custom resource for tagging function is UPDATED when tags are changing.
3. We handle tags in on_update function
4. Cluster log group is handled as well
5. Better failure handling in lambdas by actually reporting the failure
6. Cluster log enablement doesn't fail if already enabled
=> Handle update cluster scenarios in cluster tagging, k8s logs (PLAT-2515)

.github/workflows/python-app.yml, Makefile, cdk/domino_cdk/__init__.py
This PR adds the release artifacts created via `make dist` to an s3 bucket as publicly-accessible downloads.
Our current process for testing deployer integration involves creating a mutable pre-release (rc) tag in github, and iterating over it until the deployer PR is merged (at which point it becomes immutable). This is rather asinine.
With this, one can just use the s3 links CI uses to test, and then create a proper github release (still manually for now) once it's actually merged. No more iterating via github.
=> Upload release artifacts to S3 during CI

cdk/domino_cdk/provisioners/vpc.py
Although disabled is safest, that doesn't pass AWS' "security compliance" check: 
https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-ec2-8
In addition, although it seems a bit strange, we can allow the bastion to be configured with SSM if for some reason SSH doesn't work?
=> add SSM support & IMDSv2 requirement to bastion

cdk/domino_cdk/config/eks.py, cdk/domino_cdk/provisioners/ami.py, cdk/domino_cdk/provisioners/eks/eks_nodegroup.py, cdk/domino_cdk/provisioners/vpc.py
We previously hardcoded `/dev/xvda`, but that only works for AMIs where the root device name matches. If it doesn't, we end up adding a new volume with that name and can potentially not get the root device volume size we need.
This solution is definitely a bit of a PITA for a potential corner case, but it is more "correct". The only speculative issue is the root volume size, which we can't obtain programmatically, because there really isn't a good way to reference it by value.
=> support custom root device name for AMIs

.github/workflows/python-app.yml, cdk/app.py, cdk/domino_cdk/domino_stack.py
* Make nested stacks the default
* However, for TemplateAssertions (used in unit tests) still needs single stacks, since it can't work with nested stacks and nested stack resources aren't visible in the parent stack
* So keep the nest option in each provisioner
* And flip the default to nested so we can still test single stack mode for the sake of the unit tests
=> Make nested stacks default

.github/workflows/tests.yml
A conditional is missing some parens in a circumstance that only happens on the master branch. Fix the minor error.
Will probably turbomerge.
=> Master branch reports error during CI

cdk/domino_cdk/agent.py, cdk/domino_cdk/config/install.py, cdk/domino_cdk/config/template.py, cdk/tests/unit/config/__init__.py, cdk/tests/unit/config/test_config.py, cdk/tests/unit/test_agent.py
I missed the service annotation for the proxy protocol leading to a mismatch between the nginx config and ELB.
=> ensure nginx-ingress does not use proxy-protocol with istio

cdk/domino_cdk/aws_configurator.py, cdk/domino_cdk/domino_stack.py, cdk/setup.py, cdk/tests/unit/provisioners/test_aws_configurator.py
The AWS CNI does not support SELinux-enabled AMIs (https://github.com/aws/amazon-vpc-cni-k8s/issues/1291) so the only way to enable it is post-provision, but pre-install.
=> support SELinux-enabled AMIs for the VPC/CNI

cdk/domino_cdk/__init__.py, cdk/domino_cdk/config/base.py, cdk/domino_cdk/config/s3.py, cdk/domino_cdk/config/template.py, cdk/domino_cdk/provisioners/s3.py, cdk/tests/unit/config/__init__.py, cdk/tests/unit/config/test_config.py, cdk/tests/unit/config/test_s3.py, cdk/tests/unit/provisioners/test_s3.py, cdk/util.py
* Make it so that bucket _types_ are statically configured
* Adds an option to modify the bucket name in case we need to
* Adds a feature to make certain config values hidden
* Makes the bucket name override hidden so we don't clutter the config
* Removes the `-rcX` suffix from the version in code, since CI takes care of that for us now
=> PLAT-2499: Make bucket roles strict, names (sanely) configurable

cdk/app.py, cdk/domino_cdk/aws_configurator.py, cdk/domino_cdk/provisioners/eks/eks_cluster.py, cdk/setup.py, cdk/tests/unit/provisioners/test_aws_configurator.py, cdk/tests/unit/provisioners/test_eks_cluster.py
* Install coredns, kube-proxy and vpc-cni as "EKS addons"
* These are all installed by default, but unmanaged
* On EKS upgrades, these services won't get upgraded unless they're managed as addons
* Uses boto3 to get the most current version of any given addon
* You can leave the version field blank, but it won't get updated
* There is no "use the latest" function in cloudformation/cdk
* Have an alternate version that uses 3 (!!!) custom resources instead of boto3: https://github.com/dominodatalab/cdk-cf-eks/pull/62
* The CRs just feel too icky to me........
* But somebody tell me if I should just give in and do them........ ugh.
* Adds new runtime requirement of valid aws creds for aws synth, which was only required for deploy previously
=> PLAT-37: Install coredns/kube-proxy/vpc-cni addons

cdk/app.py, cdk/domino_cdk/aws_configurator.py, cdk/domino_cdk/config/iam.py, cdk/domino_cdk/provisioners/eks/eks_cluster.py, cdk/setup.py, cdk/tests/unit/provisioners/test_aws_configurator.py, cdk/tests/unit/provisioners/test_eks_cluster.py
These IAM policy bits were missed when merging the addon support.
No CDK changes, and want this in the release, so turbomerging.
=> Add EKS addon support to manual/terraform IAM perms

cdk/domino_cdk/config/template.py
Because dev_defaults is only in a single AZ, the maximum number of compute nodes total is 10. To allow better testing, 30 is best and parity with older provisioning work.
=> increase dev_defaults compute ASG max size to 30

cdk/domino_cdk/domino_stack.py, cdk/domino_cdk/provisioners/eks/__init__.py, cdk/domino_cdk/provisioners/eks/eks_iam.py, cdk/domino_cdk/provisioners/eks/eks_iam_roles_for_k8s.py, cdk/domino_cdk/provisioners/eks/eks_nodegroup.py, cdk/domino_cdk/provisioners/lambda_files/fix_missing_tags.py
There are a few items that get created which aren't automatically tagged, nor are directly taggable with CDK.
This creates a consolidated tagger for these missing items.
=> PLAT-2497: Tag untaggable things

cdk/domino_cdk/config/iam.py, cdk/domino_cdk/util.py, cdk/util.py, terraform/cloudformation.tf, terraform/variables.tf
* We seem to need the ability to describe nacls for some reason now
* Let's just `Describe*` and simplify it
* Make "disable rollback" configurable for troubleshooting / preferences
* Should this be the default, given the way we typically work? Currently still non-default...
=> PLAT-3733: Update IAM perms & add disable rollback feature to terraform

cdk/domino_cdk/config/iam.py, cdk/domino_cdk/provisioners/vpc.py
* Accounts that have never used ASGs before require extra perms to create a service linked role used with ASGs
* Added perms
* In situations where EC2 classic is still available (noticed in cloud-prod account), elastic ips created in CDK will default to ec2 classic EIPs instead of regular VPC ips.
* Explicitly define our bastion EIP to be a VPC EIP so this floating default can't cause problems.
=> PLAT-2892: Add perms to create service linked role for ASG + bastion eip fix w/ec2 classic

README.md
Some simple instructions for installing the CDK tool, as well as direction to use Python 3.9 and see the stock `aws-cdk` instructions to setup your Python environment.
=> Basic instructions for installing CDK

cdk/domino_cdk/config/iam.py, cdk/domino_cdk/provisioners/eks/eks_iam.py
[PLAT-3779](https://dominodatalab.atlassian.net/browse/PLAT-3779)
Adds `DescribeInstanceStatus` IAM policy to EC2 instances which is needed for [Shoreline](https://shoreline.io/)
=> PLAT-3779: Add DescribeInstanceStatus IAM policy

.github/workflows/tests.yml, .gitignore, cdk/domino_cdk/config/template.py, cdk/tests/unit/config/__init__.py
Set min_size for platform environment to 3 so scale up/down do not affect selenium tests. It will also keep a good size in for new development needs
=> PLAT-4675 Platform min_size to 3 on dev env

cdk/domino_cdk/config/template.py, cdk/tests/unit/config/__init__.py, cdk/tests/unit/config/test_config.py
We tried to set platform node count to match dev defaults, but didn't account for the multiple nodegroups.
=> Set dev to 3 nodes via nodegroup az count instead

terraform/cloudformation.tf
Because this totally sucks:
```
-/+ resource "aws_cloudformation_stack" "cdk_stack" {
~ disable_rollback   = false -> true # forces replacement
```
=> Add lifecycle ignore rule to disable_rollback

cdk/domino_cdk/provisioners/eks/eks_nodegroup.py
We've encountered problems scaling pods from zero when they use a PVC that's still associated with a node that was previously in the nodegroup and the cluster-autoscaler doesn't have an in-memory cache that the ASG would be able to fulfil it.
There is a tag we can add so the cluster-autoscaler can determine this, so add that.
See: https://github.com/kubernetes/autoscaler/issues/3845
=> DOM-37779: Add tag to connect asg to ebs zones

cdk/domino_cdk/config/base.py, cdk/domino_cdk/config/efs.py, cdk/domino_cdk/config/install.py, cdk/domino_cdk/config/route53.py, cdk/domino_cdk/config/s3.py, cdk/domino_cdk/domino_stack.py, cdk/tests/unit/config/test_config.py
Introduce optional `enabled` field (default `true`) to configurations for following resources:
* S3 buckets
* EFS
* Route53
* Installer configuration
This would allow the deployer to simply set `enabled: false` for each of these resource configurations to deploy a data plane VPC / EKS cluster with identical configuration as our existing dev/prod CDK flavors.
=> HBD-186: Introduce configuration fields to disable resources which aren't needed for data plane

cdk/domino_cdk/provisioners/vpc.py
Per documentation https://docs.aws.amazon.com/cdk/api/v1/python/aws_cdk.aws_ec2/VpcLookupOptions.html this is required to look up a vpc. 
Addresses PLAT-4992
=> Enable customers to bring their own vpc's

cdk/domino_cdk/provisioners/eks/eks_cluster.py
AWS-CDK's lambda for generic kubernetes manifests doesn't support 1.22 officially so `prune` bails on the missing API versions (like ingress). This occurs during updates to an existing cluster. If/when we update Calico, this may affect how the upgrades from [one version to another works](https://github.com/dominodatalab/cdk-cf-eks/blob/master/cdk/domino_cdk/aws_configurator.py).
See https://github.com/aws/aws-cdk/issues/19843 for more context. https://github.com/aws/aws-cdk/issues/15736#issuecomment-1212926265 does indicate a workaround, but it doesn't seem very palatable.
deployer_image: quay.io/domino/deployer:steved-destroy-deploy.latest
=> remove prune setting for eks cluster

cdk/domino_cdk/agent.py, cdk/tests/unit/test_agent.py
Update default Domino EKS deployment ELB cipher suite to TLS 1.2 only
before:
after:
=> DOM-32528: Update EKS nginx ELB SSL security policy

cdk/domino_cdk/agent.py
The change moving private_docker_registry under helm never made it into this.
=> Schema 1.1 fix

cdk/domino_cdk/aws_configurator.py
There are some obnoxious utf-8 quotes in the calico manifest for some reason, which get automatically converted to `?` by AWS at some point. Because of this, they _always_ present as a difference when doing `cdk diff`.
This change performs that same conversion, but within our cdk app. Because this is json, I do the same thing they do and convert it to `?` rather than `"`, as otherwise we're put in the position of iterating through every key and value individually to perform the substitutions to do it safely.
=> Dumb fix for diff false positives on calico

cdk/domino_cdk/provisioners/eks/eks_cluster.py
We are installing an older version of vpc-cni because 9 > 11
=> sort addon versions with natural numbers

cdk/domino_cdk/provisioners/lambda_files/backup_post_creation_tasks.py, cdk/domino_cdk/provisioners/lambda_files/cluster_post_creation_tasks.py, cdk/domino_cdk/provisioners/lambda_files/cluster_post_deletion_tasks.py, cdk/domino_cdk/provisioners/lambda_files/fix_missing_tags.py
When building a custom response, we were returning the resource property data which could exceed the 4k response limit.
=> update lambda to use cfnresponse

.github/workflows/tests.yml, cdk/domino_cdk/config/iam.py
kms require ListResourceTags due for EKS Secrets Envelope
=> Upgrading CDK failed with ListResourceTags missing

.github/workflows/tests.yml, cdk/domino_cdk/config/iam.py, cdk/domino_cdk/provisioners/eks/eks_iam.py
To support govcloud, the correct partition must be used when building ARNs.
=> PLAT-6040: Use partition in all arns

.github/workflows/tests.yml, cdk/domino_cdk/provisioners/eks/eks_nodegroup.py
Although the regular EKS ami sets up containerd with some cert directories, the GPU EKS ami does not.
This adds the config to setup custom ca cert support on containerd in an unmanaged nodegroup when the nodegroup type is gpu.
=> PLAT-6183: Setup containerd certs.d support on GPU nodes

cdk/domino_cdk/provisioners/eks/eks_nodegroup.py
They release the fixed GPU ami, however, it was not, in reality, fixed.
See: https://github.com/awslabs/amazon-eks-ami/issues/1154#issuecomment-1414711705
Because the incorrect version of the certs config triggers the safety valve of the old remediation, a new one is needed.
=> PLAT-6183: Update gpu remediation

cdk/domino_cdk/config/base.py, cdk/domino_cdk/domino_stack.py
Follow-up from https://github.com/dominodatalab/cdk-cf-eks/pull/129, raise an error if `install` is used in schema conversion and add a warning in the outputs.
=> add warnings and exceptions for agent template functionality

.github/workflows/test.yml, cdk/domino_cdk/provisioners/efs.py, cdk/domino_cdk/provisioners/eks/eks_cluster.py, cdk/domino_cdk/provisioners/vpc.py, convert/lib/convert.py, convert/lib/nuke.py
[PLAT-7108](https://dominodatalab.atlassian.net/browse/PLAT-7108)
cdk to terraform convert : terraform imports fail with 
```
Error: with the retirement of EC2-Classic standard domain EC2 EIPs are no longer supported
```
This is due to an upstream change in the terraform `aws` provider.
The fix is to import the `eip` resource using its allocation id rather than its public ip.
Misc Changes:
* `PRIVATE_WITH_NAT` `PRIVATE` Subnet definition deprecated.
* `JSII_SILENCE_WARNING_DEPRECATED_NODE_VERSION` reduce noise.
* Forcing the main stack into `DELETE_FAILED` used to cascade to nested stacks. Fix by iterating through nested stacks.
* Adds `ForceDelete` to ASG to mitigate:
```
botocore.errorfactory.ScalingActivityInProgressFault: An error occurred (ScalingActivityInProgress) when calling the …
```
=> PLAT-7108: import EIP using eipalloc

.github/workflows/test.yml, convert/README.md, convert/lib/convert.py
[PLAT-7427](https://dominodatalab.atlassian.net/browse/PLAT-7427)
[PLAT-7428](https://dominodatalab.atlassian.net/browse/PLAT-7428)
=> PLAT-7427 PLAT-7428 CDK migration support
