cdk/domino/domino_stack.py
We create a separate Role for each NodeGroup but they are identical.
Create one role
=> Using one IAM::Role for every NodeGroup

terraform/cloudformation.tf, terraform/s3.tf, terraform/terraform.tf, terraform/variables.tf
=> update cloudformation stack terraform lifecycle timeouts 

cdk/domino_cdk/config/__init__.py, cdk/domino_cdk/config/eks.py, cdk/domino_cdk/config_template.yaml, cdk/domino_cdk/provisioners/eks/__init__.py, cdk/domino_cdk/provisioners/eks/eks_cluster.py, cdk/tests/unit/config/__init__.py, cdk/tests/unit/config/test_config.py, cdk/tests/unit/config/test_eks.py
The change is straightforward. Add config field, use in in eks.Cluster.
=> Adding secrets encryption with KMS key (PLAT-2263)

cdk/domino_cdk/config/__init__.py, cdk/domino_cdk/provisioners/eks/eks_cluster.py, cdk/tests/unit/config/test_config.py, cdk/tests/unit/config/test_eks.py
Use AwsCustomResource to execute update function
=> Patching cluster config to enable logging (PLAT-2262)

cdk/domino_cdk/config/iam.py
=> support KMS limited IAM

cdk/domino_cdk/agent.py, cdk/domino_cdk/provisioners/vpc.py
* https://github.com/cerebrotech/platform-apps/pull/3866#discussion_r664997811
* No idea how I was testing since it doesn't appear to work at all with the previous AMI selection of Amazon Linux 1
=> ensure GPU settings are enabled and provision bastion using amazon linux 2

cdk/domino_cdk/config/iam.py
Received an error updating an existing deployment's post-creation lambda.
=> add lambda:UpdateFunctionCode to allowed perms

cdk/domino_cdk/config/base.py
Missed pushing a commit cleaning something up, realized right after merging the PR. Turbomerging.
=> Remove debug code

.github/workflows/tests.yml, cdk/domino_cdk/agent.py
helm version is no longer supported since v3 is assumed.
=> PLAT-428: Remove helm version

.github/workflows/tests.yml
Use the deployer image that is also helm 3 only
=> PLAT-428: Update deployer image from platform-apps

cdk/domino_cdk/provisioners/eks/eks_nodegroup.py, cdk/domino_cdk/provisioners/vpc.py, cdk/tests/unit/provisioners/test_vpc.py
See https://dominodatalab.atlassian.net/browse/PLAT-1118 for details
Just changing GP2->GP3 values.
=> Switch to GP3 (PLAT-1118)

cdk/domino_cdk/config/iam.py
Some recent upgrade testing has shown a few missing perms.
=> Add eks:DescribeUpdate perms

.github/workflows/tests.yml, .pre-commit-config.yaml, cdk/domino_cdk/agent.py
The template generated must be valid so it can be migrated with schema 1.2.
=> PLAT-5708: Generate a valid 1.1 agent template

cdk/domino_cdk/provisioners/eks/eks_cluster.py
Updating the vpc-cni addon up to 1.11 (which is the latest) fails for clusters still on 1.9 as it cannot be jumped more than 1 version. If we prefer the default (which is 1.10) for now, we buy ourselves some time.
See #118 for the original change.
=> prefer default addon versions over latest

cdk/domino_cdk/provisioners/eks/eks_nodegroup.py
An updated AMI was finally created, so kill this.
=> PLAT-6225: Remove GPU remediation entirely

.github/workflows/test.yml
Rather than use static credentials, set up AWS role assumption.
=> switch to GHA role assumption for temporary credentials

.github/workflows/test.yml, cdk/setup.py, convert/data/flow_logging.yaml
This resource file didn't get added when adding this feature.
=> PLAT-6464: Add flow_logging.yaml resource file

.gitignore, .pre-commit-config.yaml, cdk/setup.py, convert/data/unmanaged_nodegroup.yaml, convert/lib/convert.py, convert/terraform/main.tf.json, convert/terraform/variables.tf, convert/terraform/vpc.tf
[PLAT-6496](https://dominodatalab.atlassian.net/browse/PLAT-6496)
=> PLAT-6496 Update tf-aws-eks mod var schema

.github/workflows/tests.yml, cdk/domino_cdk/config/iam.py, cdk/domino_cdk/provisioners/s3.py
Set ownership to BucketOwnerPreferred.
=> PLAT-6563: monitoring s3 bucket object ownership

.github/workflows/test.yml, convert/README.md, convert/lib/convert.py, convert/requirements.yaml
Converts the generated json `tfvars.json` to HCL for easier manipulation, using  [tfvar].(https://github.com/shihanng/tfvar#installation)
=> Adds json to hcl tfvars convertion

.github/workflows/test.yml
=> Bump tf-aws-eks mod version
